title: The study of human body language.
description: >-
  In this course I would like to share the knowledge that I have gained
  throughout the years also I am open for q&A if anyone needs any help. It's
  hard to grasp but let's try to learn let me anyway try to teach you how to
  read text like your hearing them.
template:
  repo: the-study-of-human-body-language.-template
  name: the-study-of-human-body-language.
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
